Repository typedb/typedb-protocol, pull requests merged in 2019-10, with the labels that each got.

#14 Adapt to latest changes in bazel-distribution
  .circleci/config.yml
  grpc/java/BUILD
Labels: bug, build

#15 Refactor how version is provided to deployment rules
  .circleci/config.yml
  BUILD
Labels: build, refactor

#18 Add Void Answer Message type
  session/Answer.proto
Labels: refactor

#19 Integrate checking for unused Java dependencies
  .circleci/config.yml
  WORKSPACE
Labels: build, feature

#20 Retrievable explanations, Restrict explanations to ConceptMaps
  session/Answer.proto
  session/Session.proto
Labels: feature, refactor
