Repository typedb/typedb-protocol, pull requests merged in 2020-12, with the labels that each got.

#78 Typescript compilation
  .gitignore
  .grabl/automation.yml
  BUILD
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
  grpc/nodejs/BUILD
  grpc/nodejs/package.json
  package-lock.json
  package.json
  protobuf/BUILD
Labels: type: feature

#81 Casing fixes
  protobuf/concept.proto
Labels: priority: medium, type: bug

#84 Add session pulse and configurable timeouts
  protobuf/grakn.proto
  protobuf/options.proto
  protobuf/session.proto
Labels: priority: high, type: feature

#86 Extract rule behaviours to logic.proto from concept.proto
  grpc/java/BUILD
  grpc/nodejs/BUILD
  grpc/python/BUILD
  protobuf/BUILD
  protobuf/concept.proto
  protobuf/logic.proto
  protobuf/transaction.proto
Labels: type: refactor

#87 Fix build job
  protobuf/BUILD
Labels: priority: blocker, type: bug, type: build

#85 Add :deploy_pip to //grpc/python
  .grabl/automation.yml
  grpc/python/BUILD
Labels: priority: medium, type: build

#89 Consistent casing for enums + new npm package name
  grpc/nodejs/package.json
  package-lock.json
  package.json
  protobuf/concept.proto
Labels: priority: low, type: refactor

#90 Make grpc/python package correctly importable with pip
  grpc/python/BUILD
Labels: priority: low, type: build

#91 Make all repeated fields pluralised
  protobuf/concept.proto
  protobuf/query.proto
Labels: priority: low, type: refactor

#94 Disable RBE
  .grabl/automation.yml
Labels: priority: blocker, type: build

#93 Simplify NodeJS proto compilation
  grpc/nodejs/BUILD
Labels: priority: medium, type: refactor

#95 Use ts_grpc_compile macro to compile NodeJS TS/JS proto files
  grpc/nodejs/BUILD
  grpc/nodejs/rules.bzl
Labels: priority: high, type: build, type: refactor

#96 Build Java code to be compatible with older Java
  .bazelrc
Labels: priority: high, type: build

#98 Adapt to new Grabl syntax
  .grabl/automation.yml
Labels: priority: high, type: build, type: refactor
