Repository typedb/typedb-protocol, pull requests merged in 2020-11, with the labels that each got.

#70 Major simplification and flattening of all structures
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
  grpc/java/BUILD
  grpc/nodejs/BUILD
  grpc/python/BUILD
  protobuf/BUILD
  protobuf/answer.proto
  protobuf/concept.proto
  protobuf/database.proto
  protobuf/grakn.proto
  protobuf/options.proto
  protobuf/query.proto
  protobuf/session.proto
  protobuf/transaction.proto
Labels: priority: medium, type: refactor

#71 Add checkstyle, add release workflow in Grabl, delete CircleCI file
  .bazelrc
  .circleci/config.yml
  .gitignore
  .grabl/automation.yml
  BUILD
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/BUILD
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
  dependencies/maven/update.sh
  grpc/java/BUILD
  grpc/nodejs/BUILD
  grpc/python/BUILD
  protobuf/BUILD
  protobuf/query.proto
Labels: priority: medium, type: build

#72 Allow release to succeed in grabl
  .grabl/automation.yml
Labels: priority: medium, type: build

#73 Try to fix Grabl release
  .grabl/automation.yml
Labels: priority: medium, type: build

#74 Dissolve the 3 services back into one service named Grakn
  .grabl/automation.yml
  grpc/java/BUILD
  grpc/nodejs/BUILD
  grpc/python/BUILD
  protobuf/BUILD
  protobuf/database.proto
  protobuf/grakn.proto
  protobuf/session.proto
  protobuf/transaction.proto
Labels: priority: medium, type: refactor

#76 Allow multiple answers batched within one grpc message
  protobuf/concept.proto
  protobuf/query.proto
Labels: type: feature

#77 Upgrade gRPC to 1.33
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.snapshot
Labels: priority: medium, type: build
