Repository typedb/typedb-protocol, pull requests merged in 2020-08, with the labels that each got.

#45 bump version for release
  VERSION
Labels: priority: blocker, type: build

#44 Split Relation.Players into AllPlayers and PlayersForRoles
  protobuf/concept.proto
Labels: priority: high, type: bug

#47 Refactor Concept methods to use 'set', 'get'; rename Type.'has' to 'owns'
  protobuf/concept.proto
Labels: priority: high, type: refactor

#48 Assemble maven from bazel_distribution
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
  grpc/java/BUILD
Labels: priority: high, type: build

#49 Adapt protocol messages and their namings for 2.0 integration
  protobuf/concept.proto
  protobuf/transaction.proto
Labels: priority: high, type: bug

#50 Add RoleType.GetRelation
  protobuf/concept.proto
Labels: priority: medium, type: feature

#52 Add Type.IsRoot
  protobuf/concept.proto
Labels: priority: high, type: feature

#53 Split Concept into Thing and Type
  protobuf/answer.proto
  protobuf/concept.proto
  protobuf/transaction.proto
Labels: priority: low, type: refactor

#55 Finish splitting Concept into Thing and Type
  protobuf/concept.proto
  protobuf/transaction.proto
Labels: priority: high, type: bug

#54 Clean bazel WORKSPACE dependencies
  WORKSPACE
Labels: priority: high, type: build

#56 Remove prefilled responses from Thing/Type and slim them down to only the data necessary for a client to construct Things and Types
  protobuf/concept.proto
  protobuf/transaction.proto
Labels: priority: high, type: refactor

#59 Align Type methods in protocol with core
  .grabl/automation.yml
  protobuf/concept.proto
Labels: priority: high, type: feature, x: do not merge

#60 Refactor WORKSPACE and add filegroup declaring CI targets
  BUILD
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
Labels: type: build

#61 Delete batch_size.all
  protobuf/transaction.proto
Labels: priority: medium, type: refactor
