Repository typedb/typedb-protocol, pull requests merged in 2020-06, with the labels that each got.

#32 Remove implicits
  session/Concept.proto
Labels: priority: high, type: refactor

#35 Update gRPC, netty and other related dependencies
  dependencies/maven/artifacts/io/grpc/BUILD
  dependencies/maven/artifacts/io/opencensus/BUILD
  dependencies/maven/artifacts/io/perfmark/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
Labels: type: build

#36 Introduce Query.Options object and add `explain` option
  session/Session.proto
Labels: type: feature, type: refactor

#40 Use Ubuntu 16 CI image and update build tools
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#39 Depend on @graknlabs_dependencies
  .bazelrc
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts/com/google/android/BUILD
  dependencies/maven/artifacts/com/google/api/grpc/BUILD
  dependencies/maven/artifacts/com/google/code/findbugs/BUILD
  dependencies/maven/artifacts/com/google/code/gson/BUILD
  dependencies/maven/artifacts/com/google/errorprone/BUILD
  dependencies/maven/artifacts/com/google/guava/BUILD
  dependencies/maven/artifacts/com/google/j2objc/BUILD
  dependencies/maven/artifacts/com/google/protobuf/BUILD
  dependencies/maven/artifacts/io/grpc/BUILD
  dependencies/maven/artifacts/io/opencensus/BUILD
  dependencies/maven/artifacts/io/perfmark/BUILD
  dependencies/maven/artifacts/org/codehaus/mojo/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  dependencies/maven/update.sh
  grpc/java/BUILD
Labels: type: build
