Repository typedb/typedb-protocol, pull requests merged in 2020-09, with the labels that each got.

#62 Delete Attribute.GetValue
  protobuf/concept.proto
Labels: priority: medium, type: refactor

#63 Rename schema to encoding to match grakn 2.0
  protobuf/concept.proto
Labels: priority: high, type: refactor

#64 Rules are not types and gRPC field compaction
  protobuf/concept.proto
  protobuf/transaction.proto
Labels: priority: high, type: refactor

#66 Delete Rule.GetWhen and GetThen
  protobuf/concept.proto
  protobuf/session.proto
Labels: priority: medium, type: bug

#67 Add GetRule
  protobuf/transaction.proto
Labels: priority: medium, type: feature

#68 Create the new Query API
  grpc/java/BUILD
  grpc/nodejs/BUILD
  grpc/python/BUILD
  protobuf/BUILD
  protobuf/answer.proto
  protobuf/query.proto
  protobuf/transaction.proto
Labels: priority: medium, type: feature
