Repository typedb/typedb-protocol, pull requests merged in 2020-04, with the labels that each got.

#27 Add prefilling of various response methods
  session/Concept.proto
  session/Session.proto
Labels: priority: blocker

#24 Add a rule to explanation results
  session/Answer.proto
Labels: type: feature

#30 Upgrade to Bazel 3.0.0
  .bazelversion
Labels: priority: high, type: build

#31 Add .bazelrc
  .bazelrc
Labels: priority: high, type: build

#29 Refactor protocol for faster iterator requests
  session/Concept.proto
  session/Session.proto
Labels: type: feature, type: refactor
