Repository typedb/typedb-protocol, pull requests merged in 2021-02, with the labels that each got.

#118 Clarify Cluster service methods and introduce "preferred secondary" replica
  protobuf/cluster/cluster.proto
  protobuf/cluster/database.proto
  protobuf/cluster/grakn_cluster.proto
Labels: priority: high, type: feature

#119 Refactor code to work with latest @graknlabs_dependencies
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#120 Add methods to get and list Cluster databases
  protobuf/cluster/database.proto
  protobuf/cluster/grakn_cluster.proto
Labels: priority: high, type: feature

#122 Add inference logging option
  protobuf/options.proto
Labels: type: feature

#123 Use self-hosted Bazel cache
  .bazelrc
Labels: priority: high, type: build, type: feature

#124 Update version for alpha-10
  VERSION
Labels: priority: high, type: build
