Repository typedb/typedb-protocol, pull requests merged in 2021-01, with the labels that each got.

#99 Switch image back to default Ubuntu 20.04
  .grabl/automation.yml
Labels: type: build, type: refactor

#100 Support match, match aggregate, match group, and match group aggregate
  protobuf/answer.proto
  protobuf/query.proto
Labels: type: feature

#102 Refine the implementation of NumericGroup and Numeric
  protobuf/answer.proto
  protobuf/query.proto
Labels: type: feature

#101 Update grabl automation yaml syntax
  .grabl/automation.yml
Labels: type: build

#103 Bump year in license headers to 2021
  BUILD
  WORKSPACE
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/BUILD
  dependencies/maven/artifacts.bzl
  dependencies/maven/update.sh
  deployment.bzl
  grpc/java/BUILD
  grpc/nodejs/BUILD
  grpc/nodejs/rules.bzl
  grpc/python/BUILD
  protobuf/BUILD
  protobuf/answer.proto
  protobuf/concept.proto
  protobuf/database.proto
  protobuf/grakn.proto
  protobuf/logic.proto
  protobuf/options.proto
  protobuf/query.proto
  protobuf/session.proto
  protobuf/transaction.proto
Labels: type: build

#104 Fix checkstyle tests
  .bazelrc
  .gitignore
  .grabl/automation.yml
  dependencies/graknlabs/repositories.bzl
  grpc/python/requirements.txt
Labels: type: bug, type: build

#105 Fix the CI failing due to out-of-date Maven dependencies
  dependencies/maven/artifacts.snapshot
Labels: type: bug, type: build

#106 Rename Python protocol package to grakn-protocol
  grpc/python/BUILD
Labels: type: build, type: refactor

#108 Add GetRules to LogicManager
  protobuf/logic.proto
Labels: priority: high, type: feature

#109 Fix console warnings caused by out of date dependency
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.snapshot
Labels: type: bug

#112 Add prefetch option
  protobuf/options.proto
Labels: priority: high, type: feature

#114 Reenable remote build caching
  .bazelrc
  .grabl/automation.yml
Labels: type: build

#110 Introduce a new transaction type for reading from secondary replicas
  protobuf/cluster/database.proto
  protobuf/options.proto
Labels: type: feature

#115 Rename Python package in pip artifact to grakn_protocol
  grpc/python/BUILD
Labels: priority: medium, type: bug

#116 Add Grakn Cluster messages to pip and npm packages
  grpc/java/BUILD
  grpc/nodejs/BUILD
  grpc/python/BUILD
  protobuf/cluster/BUILD
  protobuf/cluster/grakn_cluster.proto
Labels: priority: medium, type: feature

#117 Fix pip package using wrong Python package names
  dependencies/graknlabs/repositories.bzl
  grpc/python/BUILD
Labels: priority: high, type: bug
