Repository typedb/typedb-protocol, pull requests merged in 2022-11, with the labels that each got.

#164 Re-instate use of pyenv
  .factory/automation.yml
Labels: type: build, priority: blocker, dependencies

#165 Use known working python version for GitHub deployment
  .factory/automation.yml
Labels: type: build, priority: blocker, dependencies

#168 Add Rust distribution targets and their CI workflows
  .factory/automation.yml
  dependencies/vaticle/repositories.bzl
  grpc/rust/BUILD
  grpc/rust/build.rs
  grpc/rust/lib.rs
Labels: type: feature, priority: high, x: do not merge

#171 Fix invalid `automation.yml` and update `dependencies`
  .factory/automation.yml
  dependencies/vaticle/repositories.bzl
Labels: type: bug, priority: high

#172 Fix crate snapshots failing to deploy due to bad version number
  dependencies/vaticle/repositories.bzl
Labels: type: bug, priority: high

#173 Bump Vaticle dependencies
  dependencies/vaticle/repositories.bzl
Labels: dependencies

#174 Fix Rust protocol failing to build in Cargo after an IDE sync
  .factory/automation.yml
  dependencies/vaticle/repositories.bzl
Labels: type: bug, priority: high
