Repository typedb/typedb-protocol, pull requests merged in 2023-01, with the labels that each got.

#175 Snake-case `is_root`, `is_abstract` in `Type`
  common/concept.proto
Labels: type: bug, priority: high

#176 Bump VERSION to 2.14.1
  VERSION
Labels: type: feature, priority: high

#177 Migrate to crate-universe
  WORKSPACE
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/repositories.bzl
  grpc/rust/BUILD
  grpc/rust/lib.rs
Labels: priority: blocker, dependencies
