Repository typedb/typedb-protocol, pull requests merged in 2023-05, with the labels that each got.

#182 Introduce message types to encode annotations
  common/concept.proto
Labels: type: feature, type: refactor, priority: high

#180 Introduce value query answers
  common/concept.proto
Labels: type: feature

#185 Add protocol versioning transmitted during connection open
  cluster/cluster_service.proto
  common/BUILD
  common/connection.proto
  common/version.proto
  core/BUILD
  core/core_service.proto
  grpc/java/BUILD
  grpc/nodejs/BUILD
  grpc/python/BUILD
  grpc/rust/BUILD
Labels: type: feature, priority: high
